[project]
name = 'Collective-Lucid-Dreaming-Experiment-Develop'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dream-data-storage]
path = 'contracts/dream-data-storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.experiment-protocol]
path = 'contracts/experiment-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.lucid-token]
path = 'contracts/lucid-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
